config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'home', to: 'home#index', as: 'home'

  devise_for :users

  namespace :admin do
    get '/', to: 'dashboards#index', as: 'dashboard'

    resources :schools do
      resources :klasses do
        resources :subjects
      end
    end

    get 'users', to: 'users#index'
    post 'users/:id', to: 'users#update_role', as: 'update_user_role'
  end

  get 'records', to: 'records#index', as: 'records'
  get 'records/:term', to: 'records#show', as: 'record'
  get 'records/:term/registration', to: 'records#registration', as: 'registration_records'
  patch 'records/:term/update', to: 'records#update'
  put 'records/:term/update', to: 'records#update'

  scope :registrations do
    get '/', to: 'registrations#index', as: 'registrations'
    get 'school/:id', to: 'registrations#school', as: 'registrations_school'
    get 'class/:id', to: 'registrations#klass', as: 'registrations_klass'
    post 'class/:id/authenticate', to: 'registrations#authenticate', as: 'registrations_authenticate'
  end
end

app/controllers/admin/klasses_controller.rb
class Admin::KlassesController < Admin::Base
  before_action :set_school
  before_action :set_klass, only: %i(show edit update destroy)

  def index
  end

  def show
  end

  def new
    @klass = Klass.new
  end

  def edit
  end

  def create
    @klass = Klass.new(klass_params)

    if @klass.save
      redirect_to admin_school_klass_path(@school, @klass)
      flash[:notice] =  'Klass was successfully created.'
    else
      render :new
    end
  end

  def update
    if @klass.update(klass_params)
      redirect_to admin_school_klass_path(@school, @klass)
      flash[:notice] = 'Klass was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @klass.destroy
    redirect_to admin_school_klasses_path(@school)
    flash[:notice] = 'Klass was successfully destroyed.'
  end

  private

  def set_school
    @school = School.find(params[:school_id])
  end

  def set_klass
    @klass = Klass.find(params[:id])
  end

  def klass_params
    params.require(:klass).permit(:name, :password).merge(school_id: params[:school_id].to_i)
  end
end

app/views/admin/klasses/edit.html.erb
<div class="col-sm-8 col-sm-offset-2">
  <div class="well">

    <%= form_for [:admin, @school, @klass] do |f| %>
      <fieldset>
        <legend>クラスの編集</legend>
        <% if @klass.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@klass.errors.count, "error") %> prohibited this admin_klass from being saved:</h2>

            <ul>
            <% @klass.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.label "クラス名" %><br>
          <%= f.text_field :name, class: 'form-control', onclick:'this.select();' %>
        </div>
        <div class="form-group">
          <%= f.label "パスワード" %><br>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.submit "登録", class: 'btn btn-primary' %>
        </div>
      </fieldset>
    <% end %>
  </div>

  <%= link_to '確認', admin_school_klass_path(params[:school_id], @klass) %> |
  <%= link_to '戻る', admin_school_klasses_path %>
</div>

app/views/admin/klasses/index.html.erb
<h1><%= @school.name %></h1>

<table class='table table-hover'>
  <thead>
    <tr>
      <th>クラス名</th>
    </tr>
  </thead>

  <tbody>
    <% @school.klasses.each do |klass| %>
      <tr>
        <td><%= klass.name %></td>
        <td><%= link_to '教科一覧', admin_school_klass_subjects_path(@school, klass) %></td>
        <td><%= link_to '編集', edit_admin_school_klass_path(@school, klass) %></td>
        <td><%= link_to '削除', admin_school_klass_path(@school, klass), method: :delete, data: { confirm: '本当に削除しますか?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新しいクラスの登録', new_admin_school_klass_path, class: 'btn btn-primary' %>

app/views/admin/klasses/new.html.erb
<div class="col-sm-8 col-sm-offset-2">
  <div class="well">

    <%= form_for [:admin, @school, @klass] do |f| %>
      <fieldset>
        <legend>クラスの登録</legend>
        <% if @klass.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@klass.errors.count, "error") %> prohibited this admin_klass from being saved:</h2>

            <ul>
            <% @klass.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.label "クラス名" %><br>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label "パスワード" %><br>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.submit "登録", class: 'btn btn-primary' %>
        </div>
      </fieldset>
    <% end %>
  </div>


<%= link_to 'Back', admin_school_klasses_path %>
</div>

app/views/admin/klasses/show.html.erb
<p>
  <strong>学校名:</strong>
  <%= @klass.name %>
</p>

<p>
  <strong>School:</strong>
  <%= @klass.school_id %>
</p>

<%= link_to '編集', edit_admin_school_klass_path(@school, @klass) %> |
<%= link_to '戻る', admin_school_klasses_path %><br>
<%= link_to '教科一覧', admin_school_klass_subjects_path(@school, @klass)  %>