config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'home', to: 'home#index', as: 'home'

  devise_for :users

  namespace :admin do
    get '/', to: 'dashboards#index', as: 'dashboard'

    resources :schools do
      resources :klasses do
        resources :subjects
      end
    end

    get 'users', to: 'users#index'
    post 'users/:id', to: 'users#update_role', as: 'update_user_role'
  end

  get 'records', to: 'records#index', as: 'records'
  get 'records/:term', to: 'records#show', as: 'record'
  get 'records/:term/registration', to: 'records#registration', as: 'registration_records'
  patch 'records/:term/update', to: 'records#update'
  put 'records/:term/update', to: 'records#update'

  scope :registrations do
    get '/', to: 'registrations#index', as: 'registrations'
    get 'school/:id', to: 'registrations#school', as: 'registrations_school'
    get 'class/:id', to: 'registrations#klass', as: 'registrations_klass'
    post 'class/:id/authenticate', to: 'registrations#authenticate', as: 'registrations_authenticate'
  end
end

app/models/school.rb
# == Schema Information
#
# Table name: schools
#
#  id         :integer          not null, primary key
#  name       :string
#  prefecture :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class School < ActiveRecord::Base
  has_many :klasses

  validates_presence_of :name, :prefecture
end

app/controllers/admin/schools_controller.rb
class Admin::SchoolsController < Admin::Base
  before_action :set_school, only: %i(show edit update destroy)

  def index
    @schools = School.includes(:klasses).all
  end

  def show
  end

  def new
    @school = School.new
  end

  def edit
  end

  def create
    @school = School.new(school_params)

    if @school.save
      redirect_to admin_school_path(@school)
      flash[:notice] = 'School was successfully created.'
    else
      render :new
    end
  end

  def update
    if @school.update(school_params)
      redirect_to admin_school_path(@school)
      flash[:notice] = 'School was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @school.destroy
    redirect_to admin_schools_url
    flash[:notice] = 'School was successfully destroyed.'
  end

  private

  def set_school
    @school = School.find(params[:id])
  end

  def school_params
    params.require(:school).permit(:name, :prefecture)
  end
end

app/views/admin/schools/edit.html.erb
<div class="col-sm-8 col-sm-offset-2">
  <div class="well">
    <%= form_for [:admin, @school] do |f| %>
      <fieldset>
        <legend>学校の編集</legend>

        <% if @school.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

            <ul>
            <% @school.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.label "学校名" %><br>
          <%= f.text_field :name , class: 'form-control', onclick:'this.select();' %>
        </div>
        <div class="form-group">
          <%= f.label "都道府県" %><br>
          <%= f.text_field :prefecture , class: 'form-control', onclick:'this.select();' %>
        </div>
        <div class="actions">
          <%= f.submit "新規登録", class: 'btn btn-primary'%>
        </div>
      </fieldset>

    <% end %>
  </div>
  <%= link_to '確認', admin_school_path(@school) %> |
  <%= link_to '戻る', admin_schools_path %>
</div>

app/views/admin/schools/index.html.erb
<h1>学校一覧</h1>

<table class="table table-borderd table-hover">
  <thead>
    <tr>
      <th>学校名</th>
      <th>都道府県</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schools.each do |school| %>
      <tr>
        <td><%= school.name %></td>
        <td><%= school.prefecture %></td>
        <td><%= link_to 'クラス一覧', admin_school_klasses_path(school) %></td>
        <td><%= link_to '編集', edit_admin_school_path(school) %></td>
        <td><%= link_to '削除', admin_school_path(school), method: :delete, data: { confirm: '本当に削除しますか?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新しい学校の登録', new_admin_school_path, class: 'btn btn-primary' %>

app/views/admin/schools/new.html.erb
<div class="col-sm-8 col-sm-offset-2">
  <div class="well">
    <%= form_for [:admin, @school] do |f| %>
      <fieldset>
        <legend>学校の登録</legend>

        <% if @school.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

            <ul>
            <% @school.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.label "学校名" %><br>
          <%= f.text_field :name , class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label "都道府県" %><br>
          <%= f.text_field :prefecture , class: 'form-control' %>
        </div>
        <div class="actions">
          <%= f.submit "新規登録", class: 'btn btn-primary'%>
        </div>
      </fieldset>

    <% end %>
  </div>

<%= link_to '戻る', admin_schools_path %>
</div>

app/views/admin/schools/show.html.erb
<p>
  <strong>学校名:</strong>
  <%= @school.name %>
</p>

<p>
  <strong>都道府県:</strong>
  <%= @school.prefecture %>
</p>

<%= link_to '編集', edit_admin_school_path(@school) %> |
<%= link_to '戻る', admin_schools_path %><br>
<%= link_to 'クラス一覧', admin_school_klasses_path(@school) %>