config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'home', to: 'home#index', as: 'home'

  devise_for :users

  namespace :admin do
    get '/', to: 'dashboards#index', as: 'dashboard'

    resources :schools do
      resources :klasses do
        resources :subjects
      end
    end

    get 'users', to: 'users#index'
    post 'users/:id', to: 'users#update_role', as: 'update_user_role'
  end

  get 'records', to: 'records#index', as: 'records'
  get 'records/:term', to: 'records#show', as: 'record'
  get 'records/:term/registration', to: 'records#registration', as: 'registration_records'
  patch 'records/:term/update', to: 'records#update'
  put 'records/:term/update', to: 'records#update'

  scope :registrations do
    get '/', to: 'registrations#index', as: 'registrations'
    get 'school/:id', to: 'registrations#school', as: 'registrations_school'
    get 'class/:id', to: 'registrations#klass', as: 'registrations_klass'
    post 'class/:id/authenticate', to: 'registrations#authenticate', as: 'registrations_authenticate'
  end
end

app/models/subject.rb
# == Schema Information
#
# Table name: subjects
#
#  id           :integer          not null, primary key
#  klass_id     :integer
#  name         :string
#  teacher_name :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Subject < ActiveRecord::Base
  belongs_to :klass
  has_many :records

  validates_presence_of :klass, :name
end

app/controllers/admin/subjects_controller.rb
class Admin::SubjectsController < Admin::Base
  before_action :set_school_and_klass
  before_action :set_subject, only: %i(show edit update destroy)

  def index
    @subjects = Subject.all
  end

  def show
  end

  def new
    @subject = Subject.new
  end

  def edit
  end

  def create
    @subject = Subject.new(subject_params)

    if @subject.save
      redirect_to admin_school_klass_subject_path(@school, @klass, @subject)
      flash[:notice] = 'Subject was successfully created.'
    else
      render :new
    end
  end

  def update
    if @subject.update(subject_params)
      redirect_to admin_school_klass_subject_path(@school, @klass, @subject)
      flash[:notice] = 'Subject was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @subject.records.map(&:destroy!)
    @subject.destroy!
    redirect_to admin_school_klass_subjects_path(@school, @klass)
    flash[:notice] = 'Subject was successfully destroyed.'
  end

  private

  def set_school_and_klass
    @school = School.find(params[:school_id])
    @klass = Klass.find(params[:klass_id])
  end

  def set_subject
    @subject = Subject.find(params[:id])
  end

  def subject_params
    params.require(:subject).permit(:name, :teacher_name).merge(klass_id: params[:klass_id].to_i)
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_klass
  before_action :set_subject, only: %i(show edit update destroy)

  def index
    @subjects = Subject.all
  end

  def show
  end

  def new
    @subject = Subject.new
  end

  def edit
  end

  def create
    @subject = Subject.new(subject_params)

    if @subject.save
      redirect_to subject_path(@klass, @subject)
      flash[:notice] = 'Subject was successfully created.'
    else
      render :new
    end
  end

  def update
    if @subject.update(subject_params)
      redirect_to @subject
      flash[:notice] = 'Subject was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @subject.destroy
    redirect_to subjects_url
    flash[:notice] = 'Subject was successfully destroyed.'
  end

  private

  def set_klass
    @klass = Klass.find(params[:klass_id])
  end

  def set_subject
    @subject = Subject.find(params[:id])
  end

  def subject_params
    params.require(:subject).permit(:name, :teacher_name).merge(klass_id: params[:klass_id].to_i)
  end
end

app/views/subjects/_form.html.erb
<%= form_for(@subject) do |f| %>
  <% if @subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% @subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :teacher_name %><br>
    <%= f.text_field :teacher_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form' %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Subjects</h1>

<table>
  <thead>
    <tr>
      <th>Klass</th>
      <th>Name</th>
      <th>Teacher name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.klass.name %></td>
        <td><%= subject.name %></td>
        <td><%= subject.teacher_name %></td>
        <td><%= link_to 'Show', subject_path(@klass, subject) %></td>
        <td><%= link_to 'Edit', edit_subject_path(@klass, subject) %></td>
        <td><%= link_to 'Destroy', subject_path(@klass, subject), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subject', new_subject_path %>

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= render 'form' %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Klass:</strong>
  <%= @subject.klass.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @subject.name %>
</p>

<p>
  <strong>Teacher name:</strong>
  <%= @subject.teacher_name %>
</p>

<%= link_to 'Edit', edit_subject_path(@klass, @subject) %> |
<%= link_to 'Back', subjects_path %>